### ISSUE TITLE
Update window does'nt show up

### ISSUE THREAD

**Issue by junalmeida** [hicsail/ionic-hockeyapp#15]
This is my current scenario: 

   "@ angular/common": "4.1.3",
    "@ ionic-native/core": "4.4.2",
    "ionic-angular": "3.9.2",
    "ionic-hockeyapp": "0.2.0",
    "cordova-plugin-hockeyapp": "2.2.4",

With this scenario, I can only see the updates window showing up on the android version. The ios version doesn't show the update window, although I cannot find any error message.

Things I tryed so far: 

```
1. Put some message to show when catching error: 
   this.hockeyApp.checkHockeyAppUpdates()
      .then(() => { toast.dismiss(); })
      .catch((err) => {
        this.toastCtrl.create({
          message: "Erro: " + err,
          showCloseButton: false,
          cssClass: "error",
          duration: 3000
        }).present();
      });
The catch part doesn't seem to be fired. 

Update cordova-hockeyapp to latest version 5: When I did this, android version that used to work stopped working.
```

Can you please help me? Am I missing something?

**Comment by gregfrasco** [comment]
Do you have an available .ipa on the ios hockey app with a higher version number? I don't think it returns an error if you are up to date.

**Comment by junalmeida** [comment]
@gregfrasco  Yes I have.

**Comment by junalmeida** [comment]
https://github.com/bitstadium/HockeySDK-iOS/issues/515
