### ISSUE TITLE
Ionic Native camera not working

### ISSUE THREAD

**Issue by Sam-Victor-S** [hicsail/ionic-hockeyapp#16]
After installed this hockey app plugin my native camera plugin not working.
I am using ionic 3 and angular 4 .After uninstall this plugin my native camera is working fine.Kindly give me the solution

**Comment by gregfrasco** [comment]
@victorvicky 
After installing `ionic cordova plugin add cordova-plugin-hockeyapp@latest` or `npm i --save ionic-hockeyapp`?

**Comment by Sam-Victor-S** [comment]
@gregfrasco 
After installing the ionic cordova plugin add cordova-plugin-hockeyapp@latest my camera not working.Once i removed the hockeyapp plugin it works fine.Kindly give me the solution

**Comment by gregfrasco** [comment]
This is a problem with the plugin, this repo is a typescript wrapper to provide ionic support. You should open an issue in the [plugin repo](https://github.com/bitstadium/HockeySDK-Cordova).

**Comment by Sam-Victor-S** [comment]
@gregfrasco 
Problem in which plugin?is it in HockeyApp? or Camera Plugin?
