### ISSUE TITLE
Compatibility with @ionic-native/camera

### ISSUE THREAD

**Issue by PanArnaud** [hicsail/ionic-hockeyapp#17]
Hi
I'm starting a new Ionic project with : 

- Ionic cli : 3.20.0
- Cordova : 8.0.0
- ionic-native/camera : 4.7.0

It's working until I install hockeyApp.
The camera do not works but we don't have any error log.

We probably have a compatibility problem between HockeyApp and others Ionic module.
Did anybody already face this issue ?

Thanks for your reply

**Comment by gregfrasco** [comment]
Duplicate #16
