### ISSUE TITLE
start function parameters

### ISSUE THREAD

**Issue by EralpB** [hicsail/ionic-hockeyapp#2]
Hello,

this.hockeyapp.start(androidAppId, iosAppId, false, true);

what do these parameters mean? false and true.

Can I leave iosappId null or "" if I'm building for android?

**Comment by gregfrasco** [comment]
Updated ReadMe Documentation please view the updated [How to Use](https://github.com/hicsail/ionic-hockeyapp/blob/master/README.md#how-to-use)
