### ISSUE TITLE
UpdateDialog not shown

### ISSUE THREAD

**Issue by EinfachHans** [hicsail/ionic-hockeyapp#20]
Ionic Version: 3.9.2

No errors shown, it just doesn't open...

EDIT:
Okay it's so weid.
I have an Android Smartphone where it shows the PopUp...
I build the same apk again and it does not shown in the new Version when a Update is available.

Did it takes time to recognize? Because the Version that worked now, first doesn't work either.

**Comment by AndyMDoyle** [comment]
I'm having issues with updates too.

I think it stopped working around the time iOS 12 came out, because since then I can do daily updates but the app never notifies me of any at startup. Even checking for updates manually using a Check for Updates button in the app doesn't do anything.

**Comment by syedsaadmahmood** [comment]
I'm having same issue in IOS but work great in Android.
