### ISSUE TITLE
Ionic v.4 don't use dependency ionic-angular

### ISSUE THREAD

**Issue by ebeling** [hicsail/ionic-hockeyapp#21]
I transfered my Ionic project from Ionic V3 to V4. Now I can't use ionic-hockeyapp, because of peerdependency to module 'ionic-angular'. Ionic V4 use @ionic/angular instead:

`ERROR in node_modules/ionic-hockeyapp/dist/src/hockey-app.d.ts(1,26): error TS2307: Cannot find module 'ionic-angular'.`

**Comment by iamkinetic** [comment]
@ebeling Have you found another way to use HockeyApp with Ionic 4?

**Comment by ebeling** [comment]
@iamkinetic In my Ionic4-project I now use cordova-plugin-appcenter-analytics and cordova-plugin-appcenter-crashes with @ionic-native/app-center-analytics and @ionic-native/app-center-crashes. ( see https://ionicframework.com/docs/native/app-center-analytics ) It's replacement of HockeyApp.
