### ISSUE TITLE
typings: command not found

### ISSUE THREAD

**Issue by Pettrie-ilionx** [hicsail/ionic-hockeyapp#3]
Errors during npm install
npm install ionic-hockeyapp --save

> ionic-hockeyapp@0.1.3 postinstall /Users/pbondt/Documents/node-work/inttime/node_modules/ionic-hockeyapp
> typings install

sh: typings: command not found

**Comment by Pettrie-ilionx** [comment]
Solved after installing typings
npm install typings -g

**Comment by gregfrasco** [comment]
This issue has been resolved in v0.1.6. If still experience this issue on v0.1.6 or greater please create an issue.
