### ISSUE TITLE
typings: command not found

### ISSUE THREAD

**Issue by kmp52k** [hicsail/ionic-hockeyapp#6]
While running command "npm install ionic-hockeyapp --save" I'm getting the below error:

> > ionic-hockeyapp@0.1.3 postinstall /Users/nikhilKumar/Desktop/FinReg Project/FinReg_XPlatform/node_modules/ionic-hockeyapp
> typings install

sh: typings: command not found
npm WARN @angular/router@3.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN @angular/router@3.2.4 requires a peer of @angular/common@2.2.4 but none was installed.
npm WARN @angular/router@3.2.4 requires a peer of @angular/platform-browser@2.2.4 but none was installed.
npm WARN @angular/router@3.2.4 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/compiler@2.2.4 requires a peer of @angular/core@2.2.4 but none was installed.
npm WARN @angular/compiler-cli@2.3.0 requires a peer of @angular/compiler@2.3.0 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.3.0 requires a peer of @angular/compiler@2.3.0 but none was installed.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ionic-hockeyapp" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ionic-hockeyapp@0.1.3 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ionic-hockeyapp@0.1.3 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hockeyapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hockeyapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hockeyapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nikhilKumar/Desktop/FinReg Project/FinReg_XPlatform/npm-debug.log
punitp310576D:FinReg_XPlatform nikhilKumar$

**Comment by janpio** [comment]
You should add your `ionic info` output here so the maintainer knows about your environment.

**Comment by gregfrasco** [comment]
please install typings `npm install -g typings`

**Comment by janpio** [comment]
Shouldn't this somehow be part of the plugin requirements then? Or at the very least be mentioned in the installation docs?

**Comment by gregfrasco** [comment]
I'll add it to the README, I working on an update to remove this from the requirements

**Comment by gregfrasco** [comment]
This issue has been resolved in v0.1.6. If still experience this issue on v0.1.6 or greater please create an issue.
